### ISSUE TITLE
NoSuchMethodError: 'void org.h2.engine.ConnectionInfo.<init>(java.lang.String, java.util.Properties)' with H2 2.0.202

### ISSUE THREAD

**Issue by lukaseder** [r2dbc/r2dbc-h2#203]
#### Versions

- Driver: `io.r2dbc:r2dbc-h2:0.9.0.M1` with `com.h2database:h2:2.0.202`
- Database: H2
- Java: openjdk version "17" 2021-09-14
- OS: Microsoft Windows [Version 10.0.22000.318]

#### Current Behavior

When setting up an `H2ConnectionFactory` with H2 2.0.202, I'm getting the following error:

```
java.lang.NoSuchMethodError: 'void org.h2.engine.ConnectionInfo.<init>(java.lang.String, java.util.Properties)'
	at io.r2dbc.h2.H2ConnectionFactory.getConnectionInfo(H2ConnectionFactory.java:154)
	at io.r2dbc.h2.H2ConnectionFactory.getSessionClient(H2ConnectionFactory.java:117)
	at io.r2dbc.h2.H2ConnectionFactory.lambda$new$0(H2ConnectionFactory.java:53)
	at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at org.jooq.test.setup.DatabaseSetup$1.lambda$0(DatabaseSetup.java:282)
```

This is because of an incompatible change of public (but internal?) API that the `H2ConnectionFactory` is using. The new constructor signature is:

```java
public ConnectionInfo(String u, Properties info, String user, Object password) { ... }
```
 
#### Possible Solution

There are two possible solutions that I can see:

1. This driver incompatibly upgrades to H2 2.0.202 and adapts its internals accordingly
2. The driver supports both H2 1.4 and 2.0 and attempts to call the constructor using reflection

Maybe, @katzyn has some ideas, including reverting the incompatible change? But I'd say this is internal API, so maybe, it wasn't supposed to be used?

**Comment by mp911de** [comment]
H2 2.0.202 is like a large-scale rewrite of H2 and the net result is that R2DBC H2 is entirely broken. While this is the first `NoSuchMethodError` that pops up, a huge number of value classes were renamed or follow different concepts.

**Comment by mp911de** [comment]
Paging @gregturn

**Comment by lukaseder** [comment]
> H2 2.0.202 is like a large-scale rewrite of H2 and the net result is that R2DBC H2 is entirely broken

Yeah, I'm still enjoying the rewrite of almost every query against the `INFORMATION_SCHEMA`, can imagine what it's like when you bind to the internal APIs...

**Comment by katzyn** [comment]
Hypothetically mainline H2 can have an own driver to avoid this kind of issues, but is R2DBC API for drivers already stable enough and can provide backward compatibility for older drivers like JDBC does? Will driver for R2CBC 0.9 work with 1.0?

**Comment by mp911de** [comment]
> Hypothetically mainline H2 can have an own driver to avoid this kind of issues

That would be a pretty decent way out. We could investigate a path to either transition our driver into your mainline or help you with building an R2DBC driver.

> Will driver for R2CBC 0.9 work with 1.0?

Yes, R2DBC 0.9 will be compatible with 1.0 except for a [single method removal](https://github.com/r2dbc/r2dbc-spi/blob/a8242303c76e445e2e26dacc202c681e189f2bb3/r2dbc-spi/src/main/java/io/r2dbc/spi/RowMetadata.java#L69).

**Comment by katzyn** [comment]
JDBC 4.2 (released in 2014):
> Copyright (c) 1996, 2013
> `long getLargeUpdateCount()`

R2DBC
> Copyright 2017-2019
> `Publisher<Integer> getRowsUpdated();`

Why? (There is also an `UpdateCount` interface with `long`, but I don't understand why `Integer` was chosen anyway.)

---

One a one hand, driver for R2DBC should be small enough and most likely changes in it will not be required too often. On another hand, even simple calls for tests are overcomplicated, cost of asynchronous API is high, I must say. Let me think some time about it.

**Comment by mp911de** [comment]
> > Copyright 2017-2019
> > `Publisher<Integer> getRowsUpdated();`
> 
> Why? (There is also an `UpdateCount` interface with `long`, but I don't understand why `Integer` was chosen anyway.)

Primarily, no one requested `Long` since its inception. A `Publisher` could emit multiple update counts (`Integer.MAX_VALUE`, `Integer.MAX_VALUE`, 10) to represent a large update count.

We still have possibilities to refine the spec until 1.0. Note that R2DBC SPI 0.9 GA is scheduled for Dec 6, so we won't be able to update the method signatures short term.

**Comment by lukaseder** [comment]
> A `Publisher` could emit multiple update counts (`Integer.MAX_VALUE`, `Integer.MAX_VALUE`, 10) to represent a large update count.

Please no 😅

**Comment by mp911de** [comment]
And here's the ticket to update the signature of `getRowsUpdated()`: https://github.com/r2dbc/r2dbc-spi/issues/255
